### ISSUE TITLE
Kibana doesn't load when talking to ES running in Waffle mode

### ISSUE THREAD

**Issue by foobargeez** [salyh/elasticsearch-security-plugin#18]
I am seeing that Kibana wouldn't load and throws an error saying that it failed to contact es at http://<host>:9200.

I have the following ACL in securityconfiguration:
curl -XPUT 'http://localhost:9200/securityconfiguration/actionpathfilter/actionpathfilter' -d '
{
             "rules": [
                {
                    "permission" : "ALL"
                }
              ]
}'

With the above in place, I am hoping that I should at least be able to load Kibana.  Does the above ring any bell?  Is the plugin known to work with the latest version of Kibana?

**Comment by salyh** [comment]
https://github.com/salyh/elasticsearch-security-plugin/blob/master/README.md
